package api

import (
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/prostwp/elibri-backend/internal/market"
	"github.com/prostwp/elibri-backend/internal/narrative"
)

// ── Market Mood Read ──────────────────────────────────────────────────────

// marketMoodReader is the package-level MarketMoodReader wired in from
// cmd/server/main.go via SetMoodReader. nil = serve {"read":"","source":
// "alphavizor-ai"} (frontend hides the block).
var marketMoodReader narrative.MarketMoodReader

// SetMoodReader wires the MarketMoodReader implementation called by
// handleMarketMoodRead. Called once from cmd/server/main.go. nil disables
// the LLM call entirely.
func SetMoodReader(r narrative.MarketMoodReader) { marketMoodReader = r }

// moodReadTTL is how long a fetched mood read is served before we regenerate.
// 10 minutes matches the narrative worker refresh interval — the underlying
// input (narratives + F&G) doesn't change faster than that.
const moodReadTTL = 10 * time.Minute

var (
	moodReadMu    sync.RWMutex
	moodReadCache struct {
		read string
		at   time.Time
	}
)

// resetMoodReadCache — test hook to clear the cache between cases.
func resetMoodReadCache() {
	moodReadMu.Lock()
	moodReadCache.read = ""
	moodReadCache.at = time.Time{}
	moodReadMu.Unlock()
}

// fetchFearGreedFn is the indirection used for stubbing in tests, mirroring
// fetchCryptoQuotesFn in narrative_handlers.go. By default it points at
// market.FetchFearGreed (real network + cache); the package's own test file
// overwrites it to return canned values without touching the network. NOT
// exported.
var fetchFearGreedFn = market.FetchFearGreed

// handleMarketMoodRead serves GET /api/v1/market/mood-read.
//
// Returns a 2-3 sentence neutral, observational English paragraph describing
// the OVERALL crypto market mood, generated by AlphaVizor AI (Claude Haiku)
// and filtered through the same safe-AI blacklist as the narrative idea engine.
//
// Contract: always 200 {"read":"<text or empty>","source":"alphavizor-ai"}.
// Empty "read" means the frontend should hide the block. Never 5xx — all
// upstream failures degrade to an empty or stale read.
//
// Public: no per-user data; allowlisted in internal/auth/jwt.go publicPaths.
func handleMarketMoodRead(reader narrative.SnapshotReader) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// 1. No reader wired (test mode or ANTHROPIC_API_KEY not set).
		if marketMoodReader == nil {
			writeJSON(w, map[string]interface{}{"read": "", "source": "alphavizor-ai"})
			return
		}

		// 2. Cache fast-path.
		moodReadMu.RLock()
		if !moodReadCache.at.IsZero() && time.Since(moodReadCache.at) < moodReadTTL {
			cached := moodReadCache.read
			moodReadMu.RUnlock()
			writeJSON(w, map[string]interface{}{"read": cached, "source": "alphavizor-ai"})
			return
		}
		moodReadMu.RUnlock()

		// 3. Assemble MarketMoodInput.
		fgValue, fgLabel, _ := fetchFearGreedFn() // tolerate error → label ""

		var moodNarrs []narrative.MoodNarrative
		if snaps, err := reader.LatestSnapshots(r.Context()); err == nil {
			limit := 5
			if len(snaps) < limit {
				limit = len(snaps)
			}
			for _, s := range snaps[:limit] {
				moodNarrs = append(moodNarrs, narrative.MoodNarrative{
					Name:           s.Narrative,
					Stage:          string(s.Stage),
					SentimentLabel: string(s.SentimentLabel),
					TrendScore:     s.TrendScore,
				})
			}
		}

		// 4. Skip LLM call when there is nothing to describe.
		if fgLabel == "" && len(moodNarrs) == 0 {
			writeJSON(w, map[string]interface{}{"read": "", "source": "alphavizor-ai"})
			return
		}

		in := narrative.MarketMoodInput{
			FearGreedValue: fgValue,
			FearGreedLabel: fgLabel,
			TopNarratives:  moodNarrs,
		}

		// 5. Call the reader.
		read, err := marketMoodReader.ReadMood(r.Context(), in)
		if err != nil {
			// Stale-while-error: serve last cached value if any.
			moodReadMu.RLock()
			stale := moodReadCache.read
			hasStale := !moodReadCache.at.IsZero()
			moodReadMu.RUnlock()
			if hasStale {
				writeJSON(w, map[string]interface{}{"read": stale, "source": "alphavizor-ai"})
			} else {
				writeJSON(w, map[string]interface{}{"read": "", "source": "alphavizor-ai"})
			}
			return
		}

		// 6. Store in cache (including empty-on-blacklist).
		moodReadMu.Lock()
		moodReadCache.read = read
		moodReadCache.at = time.Now()
		moodReadMu.Unlock()

		writeJSON(w, map[string]interface{}{"read": read, "source": "alphavizor-ai"})
	}
}

func handleMarketCandlesReal(w http.ResponseWriter, r *http.Request) {
	symbol := r.URL.Query().Get("symbol")
	source := r.URL.Query().Get("source") // "moex" or "binance"
	interval := r.URL.Query().Get("interval")
	limitStr := r.URL.Query().Get("limit")

	if symbol == "" {
		http.Error(w, `{"error":"symbol required"}`, http.StatusBadRequest)
		return
	}

	limit := 200
	if limitStr != "" {
		if n, err := strconv.Atoi(limitStr); err == nil {
			limit = n
		}
	}

	if source == "binance" {
		if interval == "" {
			interval = "1d"
		}
		candles, err := market.FetchCryptoCandles(symbol, interval, limit)
		if err != nil {
			http.Error(w, `{"error":"`+err.Error()+`"}`, http.StatusInternalServerError)
			return
		}
		writeJSON(w, map[string]interface{}{
			"candles": candles,
			"source":  "binance",
			"symbol":  symbol,
		})
		return
	}

	// Default: MOEX
	candles, err := market.FetchCandles(symbol, limit)
	if err != nil {
		http.Error(w, `{"error":"`+err.Error()+`"}`, http.StatusInternalServerError)
		return
	}
	writeJSON(w, map[string]interface{}{
		"candles": candles,
		"source":  "moex",
		"symbol":  symbol,
	})
}

// handleMarketFearGreed proxies CoinMarketCap's Fear & Greed index (CMC blocks
// browser CORS, so the frontend can't fetch it directly). Public, cached in
// the market package. Contract: 200 {"value":int,"label":string,"source":
// "coinmarketcap"}; on upstream failure with no cached value, 502 with
// {"error":"fear-greed upstream unavailable"}.
func handleMarketFearGreed(w http.ResponseWriter, r *http.Request) {
	value, label, err := market.FetchFearGreed()
	if err != nil {
		http.Error(w, `{"error":"fear-greed upstream unavailable"}`, http.StatusBadGateway)
		return
	}
	writeJSON(w, map[string]interface{}{
		"value":  value,
		"label":  label,
		"source": "coinmarketcap",
	})
}

// handleMarketMomentum returns relative-strength (vs BTC) over 1d/7d/30d plus a
// volume-trend read for each requested symbol, for the Crypto Sentiment
// liquidity panel. Symbols are bare tickers (no "USDT" suffix) in a CSV
// ?symbols= param. Public, backed by the 30s klines cache. Contract: 200
// {"baseline":"BTC","items":{"ETH":{"rs_1d":..,"rs_7d":..,"rs_30d":..,
// "vol_growth_pct":..}, ...}}; windows with too little history are omitted.
func handleMarketMomentum(w http.ResponseWriter, r *http.Request) {
	symbolsStr := r.URL.Query().Get("symbols")
	if symbolsStr == "" {
		http.Error(w, `{"error":"symbols required"}`, http.StatusBadRequest)
		return
	}

	symbols := strings.Split(symbolsStr, ",")
	// Cap the batch: each symbol is one (cached) klines fetch, and the panel
	// only ever asks for a handful. Guards against a pathological ?symbols=.
	const maxSymbols = 20
	if len(symbols) > maxSymbols {
		symbols = symbols[:maxSymbols]
	}

	baseline, items, err := market.FetchMomentum(symbols)
	if err != nil {
		http.Error(w, `{"error":"momentum upstream unavailable"}`, http.StatusBadGateway)
		return
	}
	writeJSON(w, map[string]interface{}{
		"baseline": baseline,
		"items":    items,
	})
}

func handleMarketQuotesReal(w http.ResponseWriter, r *http.Request) {
	symbolsStr := r.URL.Query().Get("symbols")
	source := r.URL.Query().Get("source")

	if symbolsStr == "" {
		http.Error(w, `{"error":"symbols required"}`, http.StatusBadRequest)
		return
	}

	symbols := strings.Split(symbolsStr, ",")

	if source == "binance" {
		quotes, err := market.FetchCryptoQuotes(symbols)
		if err != nil {
			http.Error(w, `{"error":"`+err.Error()+`"}`, http.StatusInternalServerError)
			return
		}
		writeJSON(w, map[string]interface{}{
			"quotes": quotes,
			"source": "binance",
		})
		return
	}

	// Default: MOEX
	quotes, err := market.FetchQuotes(symbols)
	if err != nil {
		http.Error(w, `{"error":"`+err.Error()+`"}`, http.StatusInternalServerError)
		return
	}
	writeJSON(w, map[string]interface{}{
		"quotes": quotes,
		"source": "moex",
	})
}
