package demobot

// gold_sr_golden_test.go — the Gold Agent shares the S/R clusterizer
// (supportResistanceAll, srWing, srTolPct) and prints nearest levels on its
// own card. The S/R readability rebuild (2026-09-15) changed only S/R wording,
// so gold's output must stay BYTE-IDENTICAL. The golden file was generated on
// the code BEFORE that rebuild (commit 6dbed04) and is never regenerated by the
// S/R work; regenerate only for a deliberate gold change:
//
// Regenerated once since, for the stage-2 setup structure (2026-09-16): the
// three fixture cards read an unconfirmed regime, so the only change in the
// file is one added line per card — "No setup structure without a confirmed
// regime and a last closed 1h price". Every stage-1 line is unchanged, which
// is what a diff of that regeneration has to show.
//
// Regenerated a second time for the roll disclosure (2026-09-23): one added
// line per card — goldSplicedLine — and nothing else. The stub serves every
// symbol the same bars, so both dated contracts match and the roll state is
// unknown, which reads exactly as before.
//
//	UPDATE_GOLD_GOLDEN=1 go test -run TestGoldOutputGolden ./internal/demobot/

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/prostwp/elibri-backend/pkg/types"
)

// zigzagDay is a period-12 swing with a slow drift: swing highs and lows
// every cycle, so the daily series clusters levels on both sides.
func zigzagDay(i int) (o, h, l, c float64) {
	offs := []float64{0, 18, 36, 54, 36, 18, 0, -18, -36, -54, -36, -18}
	p := 4300 + offs[i%12] + 0.4*float64(i)
	return p - 3, p + 6.3, p - 5.7, p
}

// goldSRFixture is a fixed-timestamp series for the pure clusterizer dump.
func goldSRFixture() []types.OHLCVCandle {
	start := time.Date(2026, 3, 1, 0, 0, 0, 0, time.UTC).Unix()
	out := make([]types.OHLCVCandle, 260)
	for i := range out {
		o, h, l, c := zigzagDay(i)
		out[i] = types.OHLCVCandle{Time: start + int64(i)*86400, Open: o, High: h, Low: l, Close: c, Volume: float64(100 + i%7*30)}
	}
	return out
}

var goldDates = regexp.MustCompile(`\d{4}-\d{2}-\d{2}( \d{2}:\d{2})?|\b\d{2}:\d{2}\b|\b(Mon|Tue|Wed|Thu|Fri|Sat|Sun)[a-z]*\b|\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{1,2}\b`)

func goldGoldenText(t *testing.T) string {
	t.Helper()
	var b strings.Builder

	// 1) The shared clusterizer, pure, on fixed candles.
	sup, res := supportResistanceAll(goldSRFixture(), srWing, srTolPct)
	fmt.Fprintf(&b, "supportResistanceAll supports=%d resistances=%d\n", len(sup), len(res))
	for _, l := range append(append([]SRLevel{}, sup...), res...) {
		fmt.Fprintf(&b, "  %+v\n", l)
	}

	// 2) The full Gold card at three price placements (inside, above, below
	// the clustered ladder). Dates are normalised (the stub is anchored to
	// time.Now); the weekend banner is dropped (clock-dependent).
	for _, px := range []float64{4371.3, 4520.0, 4200.0} {
		stubGoldYahoo(t, 260, zigzagDay, px)
		c := NewAgents(NewBackendClient("http://127.0.0.1:1")).GoldCard(context.Background())
		fmt.Fprintf(&b, "== price %v\nverdict: %s\nshort: %s\nstate: %s\n", px, goldDates.ReplaceAllString(c.Verdict, "<date>"), c.Short, c.State)
		for _, f := range c.Facts {
			if f == goldClosedBanner {
				continue
			}
			fmt.Fprintf(&b, "fact: %s\n", goldDates.ReplaceAllString(f, "<date>"))
		}
		fmt.Fprintf(&b, "levels: %+v\n", c.Levels)
	}
	return b.String()
}

func TestGoldOutputGolden(t *testing.T) {
	got := goldGoldenText(t)
	path := filepath.Join("testdata", "gold_sr_golden.txt")
	if os.Getenv("UPDATE_GOLD_GOLDEN") == "1" {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if got != string(want) {
		t.Errorf("gold output changed (must be byte-identical to the pre-S/R-rebuild golden)\n--- got\n%s\n--- want\n%s", got, want)
	}
}
