package whale

// worker.go — periodic ingest+score+persist loop for Whale Flow.
//
// Lifecycle (mirrors narrative.Worker):
//   1. Run() does ONE warm-start refreshAll synchronously — guarantees the
//      first request to /api/v1/whale-flow finds at least one snapshot row per
//      watched asset (even if it shows tx_count_24h=0).
//   2. Then loops on RefreshInterval ticks until ctx is cancelled.
//   3. Each tick is independent: a failure in one source (Etherscan rate-limit,
//      Mempool timeout) is logged but doesn't abort the cycle.
//
// Unlike narrative there are NO LLM phases — Whale Flow's "AI take" reasons are
// generated by the pure scorer.BuildReasons, not a model.

import (
	"context"
	"fmt"
	"log"
	"sync"
	"time"
)

// Worker drives the periodic ingest+score+persist cycle.
type Worker struct {
	Store *Store

	// Source is the primary whale-flow source. Production: EtherscanSource
	// when ETHERSCAN_API_KEY is set, else MempoolSource. Required (nil Source
	// is tolerated — refreshAll just collects from ExtraSources — but a Worker
	// with neither Source nor ExtraSources does nothing useful).
	Source WhaleFlowSource

	// ExtraSources are additional sources fanned out alongside Source each
	// tick. Production wires MempoolSource here when Etherscan is the primary,
	// so ETH (Etherscan) and BTC (Mempool) are both ingested.
	ExtraSources []WhaleFlowSource

	// RefreshInterval — how often to run refreshAll. Default 10 min if zero.
	RefreshInterval time.Duration

	// Logger optional; if nil, uses log.Default().
	Logger *log.Logger

	// fetcherCtxTimeout — per-tick wall-clock cap for ALL source fetches
	// combined. Default 30s.
	fetcherCtxTimeout time.Duration
}

const (
	// defaultRefreshInterval is the cadence applied when RefreshInterval is
	// zero. 10 min matches narrative — on-chain whale data doesn't move fast
	// enough to warrant tighter polling, and Etherscan's free quota (5 req/s,
	// 100k/day) is comfortable at this cadence × ~19 wallets × 2 actions.
	defaultRefreshInterval = 10 * time.Minute

	// defaultFetcherCtxTimeout caps one fan-out cycle. 30s = 3× each source's
	// 10s http.Client.Timeout — slack for the slowest while keeping the next
	// tick on schedule.
	defaultFetcherCtxTimeout = 30 * time.Second

	// transferFetchMinUSD is the floor for a transfer to count as a "whale"
	// move worth ingesting. 100k USD filters out retail noise while keeping
	// the genuinely large moves. Applied by the sources via minUSD.
	transferFetchMinUSD = 100_000.0

	// transferFetchLimit caps how many transfers we pull per source per tick.
	// 200 is plenty for a 10-min window of whale-sized moves and bounds the
	// insert volume.
	transferFetchLimit = 200
)

// Run blocks until ctx is cancelled. Returns the ctx error on cancellation so
// callers can distinguish "shutdown requested" from "fatal worker bug".
//
// The warm-start refresh runs synchronously BEFORE the ticker; if it fails we
// log and continue (a flaky Etherscan response on boot must not crash the
// backend).
func (w *Worker) Run(ctx context.Context) error {
	if w.Store == nil {
		return fmt.Errorf("Worker.Run: Store is nil")
	}
	interval := w.RefreshInterval
	if interval <= 0 {
		interval = defaultRefreshInterval
	}
	logger := w.logger()

	if err := w.refreshAll(ctx); err != nil {
		logger.Printf("whale_flow: warm-start failed (continuing): %v", err)
	}

	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-ticker.C:
			if err := w.refreshAll(ctx); err != nil {
				logger.Printf("whale_flow: refresh cycle error: %v", err)
			}
		}
	}
}

// refreshAll runs one full ingest+score+persist cycle. Errors from the inner
// pieces are aggregated into the summary log line rather than short-circuiting
// — ingest is best-effort by design.
func (w *Worker) refreshAll(ctx context.Context) error {
	start := time.Now()
	logger := w.logger()

	// Per-cycle context with timeout caps the source fan-out. The store-write
	// phase below uses the OUTER ctx, since DB writes should be fast and we
	// want them bound to shutdown rather than the fetcher cap. Resolved as a
	// local — never mutate the Worker struct.
	fetcherTimeout := w.fetcherCtxTimeout
	if fetcherTimeout <= 0 {
		fetcherTimeout = defaultFetcherCtxTimeout
	}
	fetchCtx, fetchCancel := context.WithTimeout(ctx, fetcherTimeout)
	defer fetchCancel()

	// ── Phase 1: parallel fetch from all sources ─────────────────────────
	transfers := w.fetchAllSources(fetchCtx, logger)

	// ── Phase 2: persist transfers (best-effort) ─────────────────────────
	// Dedup by (chain, tx_hash, to_addr) — the same as the DB constraint —
	// so a fan-out collision doesn't double-attempt the insert.
	insertedNew := 0
	seen := make(map[string]bool, len(transfers))
	for _, t := range transfers {
		key := string(t.Chain) + "|" + t.TxHash + "|" + t.ToAddr
		if seen[key] {
			continue
		}
		seen[key] = true
		inserted, err := w.Store.InsertTransfer(ctx, t)
		if err != nil {
			logger.Printf("whale_flow: InsertTransfer chain=%s tx=%s: %v", t.Chain, t.TxHash, err)
			continue
		}
		if inserted {
			insertedNew++
		}
	}

	// ── Phase 3: score + snapshot per watched asset ──────────────────────
	now := time.Now()
	since24h := now.Add(-24 * time.Hour)
	since48h := now.Add(-48 * time.Hour)

	snapsWritten := 0
	for _, asset := range WatchedAssets() {
		if err := w.refreshOneSnapshot(ctx, asset, now, since24h, since48h); err != nil {
			logger.Printf("whale_flow: snapshot %s failed: %v", asset, err)
			continue
		}
		snapsWritten++
	}

	logger.Printf("whale_flow: refreshed %d assets, ingested %d new transfers (%d fetched), took %s",
		snapsWritten, insertedNew, len(transfers), time.Since(start).Round(time.Millisecond))
	return nil
}

// refreshOneSnapshot does the per-asset score-and-persist work. Pulled out of
// refreshAll so a failure on one asset doesn't abort the rest.
func (w *Worker) refreshOneSnapshot(ctx context.Context, asset string, now, since24h, since48h time.Time) error {
	// Current 24h window.
	in24, out24, n24, byExch24, err := w.Store.InflowOutflowSince(ctx, asset, since24h, now)
	if err != nil {
		return fmt.Errorf("InflowOutflowSince 24h: %w", err)
	}
	// Prior 24h window: half-open [now-48h, now-24h).
	inPrev, outPrev, _, _, err := w.Store.InflowOutflowSince(ctx, asset, since48h, since24h)
	if err != nil {
		return fmt.Errorf("InflowOutflowSince prev-24h: %w", err)
	}

	net24 := in24 - out24
	netPrev := inPrev - outPrev
	total24 := in24 + out24

	flowPct := ComputeFlowPct(net24, netPrev)
	direction := ClassifyDirection(net24, total24)
	confidence := ComputeConfidence(n24, len(byExch24))
	// No directional flow (e.g. BTC live-feed rows are all neutral): keep the
	// "0 = too little data" sentinel honest instead of reporting a confidence
	// number for an asset we have no directional read on. Matches contract §1
	// and the handler test fixture (BTC -> confidence 0).
	if total24 == 0 {
		confidence = 0
	}

	// Source + partial badge: BTC is the live-feed (mempool) source and never
	// gets a real netflow, so its snapshot is neutral + partial. ETH/stables
	// come from Etherscan (labeled-wallet estimate → also partial).
	source := w.sourceNameForAsset(asset)
	partial := true // free-tier data is always an estimate over labeled wallets

	snap := Snapshot{
		Asset:             asset,
		CapturedAt:        now,
		NetFlowUSD24h:     net24,
		NetFlowPrev24h:    netPrev,
		FlowPct:           flowPct,
		Direction:         direction,
		InflowUSD24h:      in24,
		OutflowUSD24h:     out24,
		TxCount24h:        n24,
		Confidence:        confidence,
		ExchangeBreakdown: byExch24,
		// IsNewSpike mirrors ComputeFlowPct's sentinel predicate exactly:
		// prior window net == 0 but this window net != 0.
		IsNewSpike: netPrev == 0 && net24 != 0,
		Source:     source,
		Partial:    partial,
	}
	snap.Reasons = BuildReasons(snap)

	return w.Store.UpsertSnapshot(ctx, snap)
}

// sourceNameForAsset returns the honest source badge for a given asset's
// snapshot. BTC is served by the mempool live feed; everything else
// (ETH/USDT/USDC) by Etherscan. Falls back to the primary Source's Name when
// the asset isn't one we special-case.
func (w *Worker) sourceNameForAsset(asset string) string {
	if asset == "BTC" {
		return "mempool"
	}
	if w.Source != nil {
		return w.Source.Name()
	}
	return "etherscan"
}

// fetchAllSources fans out to Source + ExtraSources in parallel and returns
// the combined transfer list. Errors are logged but never returned — one
// source down ≠ failure. Each source is queried for every chain IT serves
// (Chains()), so an Etherscan source isn't asked for BTC and vice-versa.
func (w *Worker) fetchAllSources(ctx context.Context, logger *log.Logger) []WhaleTransfer {
	sources := make([]WhaleFlowSource, 0, 1+len(w.ExtraSources))
	if w.Source != nil {
		sources = append(sources, w.Source)
	}
	sources = append(sources, w.ExtraSources...)
	if len(sources) == 0 {
		return nil
	}

	var (
		wg  sync.WaitGroup
		mu  sync.Mutex
		all []WhaleTransfer
	)
	for _, src := range sources {
		for _, chain := range src.Chains() {
			wg.Add(1)
			go func(src WhaleFlowSource, chain Chain) {
				defer wg.Done()
				transfers, err := src.RecentWhaleTransfers(ctx, chain, transferFetchMinUSD, transferFetchLimit)
				if err != nil {
					// Best-effort: log the error but keep whatever partial set
					// the source returned alongside it.
					logger.Printf("whale_flow: %s/%s fetch error (continuing): %v", src.Name(), chain, err)
				}
				if len(transfers) == 0 {
					return
				}
				mu.Lock()
				all = append(all, transfers...)
				mu.Unlock()
			}(src, chain)
		}
	}
	wg.Wait()
	return all
}

// logger returns the Worker's logger or log.Default() when nil.
func (w *Worker) logger() *log.Logger {
	if w.Logger != nil {
		return w.Logger
	}
	return log.Default()
}
